name: build_artifacts

on:
  push:
    branches: [ main ]

jobs:
  build:    
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    
    - uses: ./.github/actions/build
      with:
        project-id: ${{ secrets.PROJECT_ID }}