name: smoke_test

on:
  workflow_dispatch:

jobs:
  build:    
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    
    - uses: ./.github/actions/smoke_tests
      with:
        project-id: ${{ secrets.PROJECT_ID }}
        without-building: true